### ISSUE TITLE
Add color by label

### ISSUE THREAD

**Issue by vzinche** [embl-cba/fiji-plugin-platyBrowser#15]
Color by column option supports only numbers. Previously it was possible to color the segmented cells by some label (e.g., the Cellular Model), that is a string. Can you please add this functionality to a new table?

**Comment by tischi** [comment]
Also here, the new version should fix this. 
Could you please test it?

**Comment by vzinche** [comment]
Yes, works, thanks!
On Tue, Apr 16, 2019 at 10:07, tischi  wrote: Also here, the new version should fix this.
 Could you please test it?
