### ISSUE TITLE
Increase the type-in window size in Color by column Min/Max

### ISSUE THREAD

**Issue by vzinche** [embl-cba/fiji-plugin-platyBrowser#16]
![Screenshot from 2019-04-15 15-18-51](https://user-images.githubusercontent.com/32451366/56144021-e6ea5100-5fa1-11e9-83cf-409f1c8c8eec.png)

**Comment by tischi** [comment]
I uploaded a new version to Fiji. 
Could you check whether it is better now?

**Comment by vzinche** [comment]
Works as well! 
On Tue, Apr 16, 2019 at 10:06, tischi  wrote: I uploaded a new version to Fiji.
 Could you check whether it is better now?
