### ISSUE TITLE
too many files

### ISSUE THREAD

**Issue by tischi** [embl-cba/fiji-plugin-platyBrowser#21]
@constantinpape
Could you guys clean up a bit?
<img width="333" alt="image" src="https://user-images.githubusercontent.com/2157566/56675030-7935d780-66bb-11e9-933b-dec08f98d814.png">
:-)

**Comment by tischi** [comment]
Thanks a lot!
I am sorry for being so pedantic about it!
The remaining one is from me :-) I will remove it!

**Comment by tischi** [comment]
Thanks a lot!!!

**Comment by constantinpape** [comment]
Sure ;).
Let's close this issue for now?

I have opened #23 to collect ideas on how to deal with changes in the segmentation(s) due to manual proof-reading, which we started to discuss in the meeting today.
