### ISSUE TITLE
Please remove the appearance of 3D object just on click

### ISSUE THREAD

**Issue by vzinche** [embl-cba/fiji-plugin-platyBrowser#22]
It is incredibly annoying when I just want to go through the table, especially when it gives you the warning that the cell is too big to be displayed.
Additionally, when a couple of cells are already selected, and you select a new one, it apparently gives you the warning message for ALL of them one by one :D
Please see the gif attached (watch as gif) :)
![annoying](https://user-images.githubusercontent.com/32451366/57309322-30811400-70e8-11e9-9db9-267abe9a49c8.gif)

**Comment by tischi** [comment]
Yes, that is annoying!
Let's discuss your use case today in the meeting!
Maybe a general checkbox in the UI could be good:

* [X] View selected objects in 3D

What do you think?

**Comment by vzinche** [comment]
Yes, I think a checkbox is a good idea!
On Wed, May 8, 2019 at 09:02, tischi  wrote: Yes, that is annoying!
 Let's discuss your use case today in the meeting!
 Maybe a general checkbox in the UI could be good:
	*  View selected objects in 3D 

What do you think?

**Comment by tischi** [comment]
Done. Please test!
<img width="587" alt="image" src="https://user-images.githubusercontent.com/2157566/57372448-fec68680-7195-11e9-955c-3a2a39cd95c1.png">
