### ISSUE TITLE
Access to folders with old files

### ISSUE THREAD

**Issue by tischi** [embl-cba/fiji-plugin-platyBrowser#24]
@constantinpape

Could you please give people write access to those folders?

```
drwxr-xr-x 2 pape    kreshuk   4096 May  8 14:47 bkp/
drwxrwxrwx 3 pape    kreshuk   4096 Apr 10 17:08 label_attributes/
drwxr-xr-x 2 pape    kreshuk  32768 Feb 19 16:51 old-meds/
drwxr-xr-x 2 pape    kreshuk  24576 Feb 11 11:08 old_alignment/
drwxr-xr-x 2 pape    kreshuk   4096 Feb 12 12:59 old_segmentation/
```

I need to move some stuff there...

Thanks!

**Comment by constantinpape** [comment]
Please check now, should be done.

**Comment by tischi** [comment]
yes. thanks!

The only thing left now seem to be to rename those guys:

```
-rw-r--r-- 1 pape    kreshuk    11335638422 Apr  3 09:20 em-segmented-cells-labels-new-uint16.h5
-rw-r--r-- 1 pape    kreshuk           1081 Apr  3 09:20 em-segmented-cells-labels-new-uint16.xml
```

Could you still do it? And once you have the final segmentation you could move them into the `old_segmentations` folder. Maybe into a sub-folder with a date or something such that we do not need to change the filenames again, which is a bit annoying because of the internal reference in the xml.

**Comment by constantinpape** [comment]
I gave you write permissions for these files.
From my side you can rename them however you like, but I don't know if and how @K-Meech
or @vzinche are using them.

**Comment by vzinche** [comment]
Hey!
I am fine with renaming it now
On Fri, May 10, 2019 at 13:16, Constantin Pape  wrote: I gave you write permissions for these files.
 From my side you can rename them however you like, but I don't know if and how @K-Meech (https://github.com/K-Meech)
 or @vzinche (https://github.com/vzinche) are using them.

**Comment by tischi** [comment]
login 15% mv em-segmented-cells-labels-new-uint16.h5 em-segmented-cells-labels.h5
login 16% mv em-segmented-cells-labels-new-uint16.xml em-segmented-cells-labels.xml
