### ISSUE TITLE
CRASH: browser crashes while loading 

### ISSUE THREAD

**Issue by vzinche** [embl-cba/fiji-plugin-platyBrowser#27]
Browser crashes both while choosing the local and remote storage of data (attached
![local](https://user-images.githubusercontent.com/32451366/58325177-45201480-7e29-11e9-844b-91c6e4b43799.png)
![remote](https://user-images.githubusercontent.com/32451366/58325243-6b45b480-7e29-11e9-8f3e-d54bbdd600fa.png)

)

**Comment by tischi** [comment]
I'll fix it later today. Have to go to a meeting now...

**Comment by tischi** [comment]
Could you update and try again?

**Comment by vzinche** [comment]
The local works now, the remote still doesn't
