### ISSUE TITLE
Add_feature: support multiple tables

### ISSUE THREAD

**Issue by vzinche** [embl-cba/fiji-plugin-platyBrowser#28]
I have left only the minimal table data in the table file (/g/arendt/EM_6dpf_segmentation/EM-Prospr/tables/em-segmented-cells-20190520-labels.csv)

The genes were moves into /g/arendt/EM_6dpf_segmentation/EM-Prospr/tables/em-segmented-cells-20190520-labels_genes.csv

**Comment by constantinpape** [comment]
This should be done in accordance with the new table layout, see https://git.embl.de/tischer/platy-browser-tables/tree/dev/data/0.0.0/tables/sbem-6dpf-1-whole-segmented-cells-labels.
