### ISSUE TITLE
Bug, not urgent: segmentation labels can't be turned off from main window

### ISSUE THREAD

**Issue by vzinche** [embl-cba/fiji-plugin-platyBrowser#29]
When you load a segmentation into the Browser, previously you could uncheck the box next to the name (see pic attached) in the main window, and the labeling would not be displayed. Now it still works for normal files, but not for the ones with the corresponding table (segmented cells or nuclei.
![Screenshot from 2019-06-03 16-07-19](https://user-images.githubusercontent.com/32451366/58808536-7e6f3600-861a-11e9-92ab-500134f7b1a1.png)
)

**Comment by constantinpape** [comment]
@tischi Can I bring this one to your attention again? It's still an issue and makes exploring different
segmentations with the platy browser very inconvenient.

**Comment by tischi** [comment]
I will fix this today!

**Comment by tischi** [comment]
Please update and test.

**Comment by constantinpape** [comment]
Yes, works now.
Thanks!
