### ISSUE TITLE
Bookmark functionality

### ISSUE THREAD

**Issue by constantinpape** [embl-cba/fiji-plugin-platyBrowser#30]
It would be very helpful to add functionality for persistent bookmarks.
The base functionality seems to be already there (`Move to` -> `Left eye`),
but it would be very helpful to expose creating new bookmarks to users.

There is already some bookmark functionality described in the Help window
(`Shift B`, `B`, `O`), but I couldn't figure out how to make this work / if it still works.

**Comment by tischi** [comment]
> add functionality for persistent bookmarks.
We could do this and store them automatically in the ImageJ Prefs file. However, whenever a user has to reinstall Fiji that is likely lost. Do you have a suggestion where the store them in an even more persistent way?

**Comment by constantinpape** [comment]
> Do you have a suggestion where the store them in an even more persistent way?

Yes, we could store them in the platy folder. I am working on the new file structure anyways, and this would fit well in `misc/`.

I would just store them as `bookmarks.json` with content
```
{'name': {'position': [x, y, z], 'view': [...]}}
```

**Comment by tischi** [comment]
And for external (non-EMBL) people?
Or are you thinking just about us for the moment?

**Comment by constantinpape** [comment]
> And for external (non-EMBL) people?

If I understood our plans correctly, we would have the whole folder structure exposed
via a http server, so external people should be able to read it as well.

**Comment by tischi** [comment]
Nope, the images will be served through [BigDataServer](https://imagej.net/BigDataServer).
And the tables will be served via GitLab:  https://git.embl.de/tischer/platy-browser-tables
We could put the coordinates also in GitLab. Would make sense because then, if people work on a fork, they have write access as well and could add their own coordinates.

**Comment by constantinpape** [comment]
> Nope, the images will be served through [BigDataServer](https://imagej.net/BigDataServer).

Yes, but I thought this would have an http server backend. We probably need to discuss the details of this in person.

> We could put the coordinates also in GiLab. Would make sense because then, if people work on a fork, they have write access as well and could add their own coordinates.

Yes, this makes a lot of sense. The whole new folder structure will be on gitlab anyways.

Let's conclude that we will find a way to store this via gitlab.
We should discuss the details of this and the new folder structure in general (see [spec](https://git.embl.de/tischer/platy-browser-tables/tree/dev#data-storage) and [example](https://git.embl.de/tischer/platy-browser-tables/tree/dev#data-storage)) once you're back at EMBL.

**Comment by tischi** [comment]
I am at EMBL. But there is a course running this week. A bit crazy.
Do you have time on Friday?

**Comment by constantinpape** [comment]
> I am at EMBL. But there is a course running this week. A bit crazy.
> Do you have time on Friday?

Oh ok, I thought you are away already.
Yes, Friday is fine with me any time.

**Comment by tischi** [comment]
I was away, but back in-between.
Let's say 9:30?

**Comment by constantinpape** [comment]
> Let's say 9:30?

Fine with me. I can drop by your office then.

**Comment by constantinpape** [comment]
I added a bookmark example file:
https://git.embl.de/tischer/platy-browser-tables/blob/dev/data/0.0.0/misc/bookmarks.json

**Comment by tischi** [comment]
done. i guess.
