### ISSUE TITLE
Use master branch of platy-browser-data repository

### ISSUE THREAD

**Issue by constantinpape** [embl-cba/fiji-plugin-platyBrowser#33]
The platy-browser is currently set to the dev branch of the [data repository](https://git.embl.de/tischer/platy-browser-tables). This branch was already merged into master and is not up-to-date
anymore, so does not contain the latest data versions.
@tischi please use the master instead.

**Comment by tischi** [comment]
done. the default is now the master.

**Comment by constantinpape** [comment]
@tischi my fiji does not update platy browser yet.
Did you forget to push the version or does it just take some time to take effect?

**Comment by tischi** [comment]
I did not push yet, because I need to implement automated detection of versions first.
