### ISSUE TITLE
Highly binarized non-binary images

### ISSUE THREAD

**Issue by HernandoMV** [embl-cba/fiji-plugin-platyBrowser#38]
Specifically, ProSPr-Ref seems kind of binary and the changes in the brightness do not cover the full range of the intensities of the original image

**Comment by constantinpape** [comment]
This is partly related to #39 and some of this should be fixed now.

However, I am a bit confused about which of the ProSPR data is non-binary:
In the registration step, I am using nearest neighbor interpolation for all prospr volumes.
Currently, we have the MEDs, the segmented ProSPR regions and the ProSPR ref.
Which of these signals is not binary?
(We also have VCs and while these are not binary, they are integer labels, so we also need nearest neighbor interpolation here.)

**Comment by HernandoMV** [comment]
The ProSPr ref is what I was referring to.

**Comment by constantinpape** [comment]
> The ProSPr ref is what I was referring to.

Ok, so of all the files we are registering only the ProSPr ref is non-binary / not a label image.
I will adjust this at some point soon then.
