### ISSUE TITLE
highly saturated colors

### ISSUE THREAD

**Issue by HernandoMV** [embl-cba/fiji-plugin-platyBrowser#39]
Colors seem highly saturated (e.g. choosing a green color looks yellow) and the MEDs look better if the brightness uses the full range. This might relate to the other issue of the brightness scale.

**Comment by constantinpape** [comment]
The reason for this is that I accidentally changed something in how the MED files are stored.
(The underlying reason being that BigDataViewer can't deal with unsigned data types, which makes it very annoying to work with it from the python site).
Anyway, I have fixed this now and the colors should be back to normal.

**Comment by tischi** [comment]
closing. hope it's fine.
