### ISSUE TITLE
Format for version readmes

### ISSUE THREAD

**Issue by constantinpape** [embl-cba/fiji-plugin-platyBrowser#42]
We have discussed to add Readme files for the individual versions, that contain a summary of the changes for each version.
I have added two examples now ([here](https://git.embl.de/tischer/platy-browser-tables/blob/master/data/0.6.3/README.txt) and [here](https://git.embl.de/tischer/platy-browser-tables/blob/master/data/0.6.2/README.txt)).

I would suggest a format similar to the recommended github commit message format:
```
Brief summary up to 100 signs

More extended description. Can span multple
lines and should elaborate on the brief summary in
the header.
```

@tischer Let me know if this is ok with you, then I will add this to the other versions as well.

**Comment by tischi** [comment]
Ok for me!
