### ISSUE TITLE
Loss of resolution retrieving screen data

### ISSUE THREAD

**Issue by HernandoMV** [embl-cba/fiji-plugin-platyBrowser#44]
Pressing 'C' extracts the data. In some cases, the image retrieved is at a wrong scale. For instance, specifying 0.02 resolution for the retrieved image, spits an image whose properties are indeed 0.02 resolution, but it is wrong (e.g. things are smaller than they actually are). There must be a bug somewhere...
![image](https://user-images.githubusercontent.com/6049065/70910681-15746c00-2008-11ea-82ab-1e28cdffff27.png)

**Comment by tischi** [comment]
@HernandoMV 
But the region that is captured is the same as what you see in the bdv, right?
Could you find out what is wrong?

1. are the pixels in the captured image of the specified size, but the image properties are wrong, or
2. are the pixels of the wrong size 

You could probably see this be zooming in quite a bit and checking whether one pixel has the correct dimensions. I tried to figure this out by looking at my code but I could not..

**Comment by tischi** [comment]
And you say "in some cases". Does that mean it does not happen always?

**Comment by HernandoMV** [comment]
is the second option. If I ask for 0.02 um/px, that's what is written in the image properties. However, when I put the scale bar this is totally off. I am not sure that it doesn't happen always. Sometimes (e.g. if I ask for 0.01nm/px), it looks right by eye and scale bar, but I cannot be 100% sure.

**Comment by tischi** [comment]
I will check!

**Comment by tischi** [comment]
@HernandoMV 
I found a few issues... 
Could you please update and see whether it is fixed now?

**Comment by HernandoMV** [comment]
@tischer it works fine now. Thanks!
