### ISSUE TITLE
Bdv view capture exports wrong colors

### ISSUE THREAD

**Issue by vzinche** [embl-cba/fiji-plugin-platyBrowser#47]
I load the segmentation, use 'color by column COLUMN_NAME' and choose viridis color scheme.
Then I click C (capture) and that's how the capture looks like (original bdv on the left, capture on the right):

![Screenshot from 2020-02-05 10-11-36](https://user-images.githubusercontent.com/32451366/73827671-469b3c80-4800-11ea-9a45-ef27b458c4da.png)

I guess (besides being oversaturated) it still colors by the first column instead of the column that I've chosen.

**Comment by tischi** [comment]
OK. Took me couple of hours but I have now a new solution: 
<img width="1191" alt="image" src="https://user-images.githubusercontent.com/2157566/73865624-d910ff80-4843-11ea-9229-8313d0aee36f.png">
I show two images. One is an RGB image that should look exactly as the one in the BDV. The other one contains only Gray-values and no colors. The gray values corresponding to the underlying raw data.

1. What do you think?
1. Could you please ping Hernando? I could not find his GitHub handle...

**Comment by constantinpape** [comment]
cc @HernandoMV

**Comment by HernandoMV** [comment]
Hi, I am not sure what is required from me here. I think I am missing something...

**Comment by tischi** [comment]
...also works for Viridis LUT and in the PlatyBroswer :-)

<img width="1037" alt="image" src="https://user-images.githubusercontent.com/2157566/73868813-728ee000-4849-11ea-8684-908acc5a632c.png">

**Comment by HernandoMV** [comment]
It worked for me fine if that is why you ping(ed?) me.

**Comment by tischi** [comment]
@HernandoMV It is about making screenshots within the PlatyBrowser. You were also a main customer. And there was, also for you, the issue that the cell segmentations did you have the correct colours...

**Comment by HernandoMV** [comment]
I tried to do it just for fun with random colors, and that never worked. I don't think we ever figured out why. Maybe something about 8 vs 16 bit?
When I did it for separate channels (eg gene expression) then there was no problem

**Comment by tischi** [comment]
> I tried to do it just for fun with random colors, and that never worked. I don't think we ever figured out why. Maybe something about 8 vs 16 bit?

The point is that I figured out one way to do it. So I just wanted to inform you and also ask if that's ok for you (with the two images as described above, and also as shown below again).

<img width="1059" alt="image" src="https://user-images.githubusercontent.com/2157566/73869221-360fb400-484a-11ea-8dfc-97e993140a84.png">

**Comment by HernandoMV** [comment]
Ok now I am more confused! hahaha. So it should work now? "if that's ok for you" meaning if it works for me?

**Comment by tischi** [comment]
ok. from the start :-)

The output of the screenshot used to be one stack of 16 bit images, where we tried to assign each image the same color as in bdv. However, this was not possible for more complicated colour schemes, such as colouring of the cell segmentation.

New solution: there still is the stack of 16 bit images, but they have now no colour at all. They are all grayscale. So, people could try to colour these images themselves, change brightness and contrast or just look at the raw pixel values. However there is now also a second RGB image, which looks like what one sees in the BigDataViewer window. This image cannot be modified, i.e. no brightness and contrast adjustments can be made. That means all the adjustments would have to be done in the BigDataViewer window beforehand. 

1. Understandable? :-)
2. Do you think this is good? Or should I change something?

**Comment by HernandoMV** [comment]
Ohhh I see now. Thanks. I think this is great!

**Comment by vzinche** [comment]
I didn't fully get why we need two output images (raw and RGB), but as long as it works it's fine with me :)

**Comment by tischi** [comment]
> I didn't fully get why we need two output images (raw and RGB), but as long as it works it's fine with me :)

Well, that's the question. It may be confusing to beginner users, but to people that really care about the gray values it is great to be able to get them. So, I am not sure. That's why I brought it up.

Opinions?

**Comment by vzinche** [comment]
Still don't get it :(
If they want the underlying grey values can't they just switch off the added genes/segmentations/etc?
Also, do I get it right, the RGB images also has the underlying raw data, right? It's not that you have to add them afterwards?

**Comment by tischi** [comment]
In the new version `C` will just show the RGB image and `Shift + C` will show both the RGB image and raw data channel stack. I think that fixes it.
