### ISSUE TITLE
Position keyboard shotcut P throws an exception (works, though)

### ISSUE THREAD

**Issue by vzinche** [embl-cba/fiji-plugin-platyBrowser#48]
Pressing P shows the position and view in the log, but throws an exception to the console:

![Screenshot from 2020-02-05 10-26-40](https://user-images.githubusercontent.com/32451366/73828737-15bc0700-4802-11ea-9ff8-db640d57ca0c.png)

**Comment by tischi** [comment]
should be fixed with latest version.
