### ISSUE TITLE
3D view of cell AND nucleus

### ISSUE THREAD

**Issue by tischi** [embl-cba/fiji-plugin-platyBrowser#6]
@constantinpape

I just got very excited because I found that the 3DViewer API allows having multiple objects with different transparency. So, if both nucleus and cell label masks are active we can probably, upon `ctrl+shift+click` show both the cell and the nucleus in one 3D viewer window, and even make the cell a bit more transparent such that one can see the nucleus inside. Isn't that amaaaaazing? :-)

Just a demo (not real data):
<img width="509" alt="image" src="https://user-images.githubusercontent.com/2157566/56023785-f9992780-5d0e-11e9-8400-d8ea2a807799.png">

**Comment by constantinpape** [comment]
Yes, that would be amazing!
We could also use this for other structures; e.g. cilia which I am segmenting right now.

**Comment by tischi** [comment]
I am working on making the whole 3D View aspect more professional and 

1. I feel it would be good to precompute the meshes (i.e. a list of some coordinates on the surface).
1. Maybe the simplest (to start with) would be if those meshes were a column in the table text file, maybe just a space separated list of voxel coordinates: `2 2 2 3 4 5 3 2 4 9 10 12` with the meaning `x0 y0 z0 x1 y1 z1 x2 y2 z2 ...`. Probably there are more clever ways, e.g. storing only differences to a starting point (https://stackoverflow.com/questions/283299/best-compression-algorithm-for-a-sequence-of-integers) 

What do you think?

**Comment by constantinpape** [comment]
>     1. I feel it would be good to precompute the meshes (i.e. a list of some coordinates on the surface).

Yes, that sounds like a good idea if you want to improve performance.

>     2\. Probably there are more clever ways, e.g. storing only differences to a starting point

For performance / efficient storage it might also help to serialize a (compressed) byte stream instead of the table version.

**Comment by tischi** [comment]
progress:

<img width="1068" alt="image" src="https://user-images.githubusercontent.com/2157566/56133906-c3b5a680-5f8d-11e9-9bf4-bb53fcd2acf6.png">

**Comment by tischi** [comment]
Testimonials :-)
F******uck!!!!! XD
OMFG!
Amazing!!!
